mkdir -p ALL_PDFs
cd ALL_PDFs

wget -O 01.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/preface.pdf
wget -O 02.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/toc.pdf
wget -O 03.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/dialogue-threeeasy.pdf
wget -O 04.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/intro.pdf
wget -O 05.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/dialogue-virtualization.pdf
wget -O 06.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-intro.pdf
wget -O 07.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-api.pdf
wget -O 08.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-mechanisms.pdf
wget -O 09.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-sched.pdf
wget -O 10.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-sched-mlfq.pdf
wget -O 11.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-sched-lottery.pdf
wget -O 12.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-sched-multi.pdf
wget -O 13.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-dialogue.pdf
wget -O 14.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/dialogue-vm.pdf
wget -O 15.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/vm-intro.pdf
wget -O 16.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/vm-api.pdf
wget -O 17.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/vm-mechanism.pdf
wget -O 18.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/vm-segmentation.pdf
wget -O 19.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/vm-freespace.pdf
wget -O 20.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/vm-paging.pdf
wget -O 21.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/vm-tlbs.pdf
wget -O 22.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/vm-smalltables.pdf
wget -O 23.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/vm-beyondphys.pdf
wget -O 24.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/vm-beyondphys-policy.pdf
wget -O 25.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/vm-complete.pdf
wget -O 26.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/vm-dialogue.pdf
wget -O 27.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/dialogue-concurrency.pdf
wget -O 28.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/threads-intro.pdf
wget -O 29.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/threads-api.pdf
wget -O 30.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/threads-locks.pdf
wget -O 31.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/threads-locks-usage.pdf
wget -O 32.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/threads-cv.pdf
wget -O 33.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/threads-sema.pdf
wget -O 34.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/threads-bugs.pdf
wget -O 35.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/threads-events.pdf
wget -O 36.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/threads-dialogue.pdf
wget -O 37.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/dialogue-persistence.pdf
wget -O 38.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/file-devices.pdf
wget -O 39.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/file-disks.pdf
wget -O 40.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/file-raid.pdf
wget -O 41.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/file-intro.pdf
wget -O 42.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/file-implementation.pdf
wget -O 43.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/file-ffs.pdf
wget -O 44.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/file-journaling.pdf
wget -O 45.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/file-lfs.pdf
wget -O 46.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/file-ssd.pdf
wget -O 47.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/file-ssd.pdf
wget -O 48.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/file-dialogue.pdf
wget -O 49.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/dialogue-distribution.pdf
wget -O 50.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/dist-intro.pdf
wget -O 51.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/dist-nfs.pdf
wget -O 52.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/dist-afs.pdf
wget -O 53.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/dist-dialogue.pdf
wget -O 54.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/dialogue-security.pdf
wget -O 55.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/security-intro.pdf
wget -O 56.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/security-authentication.pdf
wget -O 57.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/security-access.pdf
wget -O 58.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/security-crypto.pdf
wget -O 59.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/security-distributed.pdf
wget -O 60.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/dialogue-vmm.pdf
wget -O 61.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/vmm-intro.pdf
wget -O 62.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/dialogue-monitors.pdf
wget -O 63.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/lab-tutorial.pdf
wget -O 64.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/lab-projects-systems.pdf
wget -O 65.pdf https://pages.cs.wisc.edu/~remzi/OSTEP/lab-projects-xv6.pdf

pdftk $(ls -v *.pdf) cat output ../Operating_Systems_Three_Easy_Pieces.pdf
